name: Deploy Discord Bot to Azure

on:
  push:
    branches:
      - main  # or "master" depending on your repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linter (optional)
        run: |
          python -m compileall .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2  # use @v2 to avoid v3 timeout issues
        with:
          app-name: VUKBot      # <-- replace this
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
